#!/bin/bash

# get free memory
IFS=" " read USED FREE TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})
# get processors
PROCESSOR_NAME=`grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1`
PROCESSOR_COUNT=`grep -ioP 'processor\t:' /proc/cpuinfo | wc -l`

W="\e[0;39m"
G="\e[1;32m"

echo -e "${W}CPU.........: $W$PROCESSOR_NAME ($G$PROCESSOR_COUNT$W vCPU)
${W}Memory......: $G$USED$W used, $G$FREE$W free, $G$TOTAL$W total$W"
